force-app/main/default/objects/Object_Lock__c/Object_Lock__c.object-meta.xml
<CustomObject>
    <label>Object Lock</label>
    <nameField>
        <displayFormat>OBJLCK-{0000}</displayFormat>
        <label>Object Lock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Locks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Lock__c/fields/Expires_At__c.field-meta.xml
<CustomField>
    <fullName>Expires_At__c</fullName>
    <description>Time after which this lock is no longer valid.</description>
    <label>Expires At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Object_Lock__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user that owns this lock.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Object_Locks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LockedObjectTriggerHandlerTest.cls
@isTest
public with sharing class LockedObjectTriggerHandlerTest {
    
    @isTest
    public static void test_afterUpdate_lockExpired() {
        Account testAccount = insertTestAccount();

        RecordLocker locker = new RecordLocker(new LockValidatorMock(true));
        locker.lockRecord(new RecordLocker.LockRequest(testAccount.Id));

        // Find the lock and update it to have been expired.
        Object_Lock__c testLock = [SELECT Expires_At__c FROM Object_Lock__c LIMIT 1];
        testLock.Expires_At__c = Datetime.now().addMinutes(-5);
        update testLock;

        Test.startTest();

        testAccount.Description = 'Test description';
        update testAccount;

        Test.stopTest();

        System.assert(true, 'Expected to be able to save the record with our own expired lock.');
    }

    @isTest
    public static void test_afterUpdate_lockedByOther() {
        Account testAccount = insertTestAccount();

        RecordLocker locker = new RecordLocker(new LockValidatorMock(true));
        locker.lockRecord(new RecordLocker.LockRequest(testAccount.Id));

        // Find the lock and update it to not be owned by the current user.
        Object_Lock__c testLock = [SELECT User__c FROM Object_Lock__c LIMIT 1];
        testLock.User__c = null;
        update testLock;

        Test.startTest();

        try {
            testAccount.Description = 'Test description';
            update testAccount;

            System.assert(false, 'Expected to get an error attempting to save the record locked by another user.');
        }
        catch (DmlException e) {
            System.assert(true);
        }

        Test.stopTest();
    }

    @isTest
    public static void test_afterUpdate_lockedByOtherExpire() {
        Account testAccount = insertTestAccount();

        RecordLocker locker = new RecordLocker(new LockValidatorMock(true));
        locker.lockRecord(new RecordLocker.LockRequest(testAccount.Id));

        // Find the lock and update it to have been expired and to not be owned by the current user.
        Object_Lock__c testLock = [SELECT Expires_At__c, User__c FROM Object_Lock__c LIMIT 1];
        testLock.Expires_At__c = Datetime.now().addMinutes(-5);
        testLock.User__c = null;
        update testLock;

        Test.startTest();

        testAccount.Description = 'Test description';
        update testAccount;

        Test.stopTest();

        System.assert(true, 'Expected to be able to save the record with the expired lock.');
    }

    private static Account insertTestAccount() {
        Account a = new Account(Name = 'Test Account');
        insert a;

        return a;
    }
}