force-app/main/default/objects/Object_Lock__c/Object_Lock__c.object-meta.xml
<CustomObject>
    <label>Object Lock</label>
    <nameField>
        <displayFormat>OBJLCK-{0000}</displayFormat>
        <label>Object Lock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Locks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Lock__c/fields/Expires_At__c.field-meta.xml
<CustomField>
    <fullName>Expires_At__c</fullName>
    <description>Time after which this lock is no longer valid.</description>
    <label>Expires At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Object_Lock__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user that owns this lock.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Object_Locks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LockerUtil.cls
public with sharing class LockerUtil {

    public static Boolean doesCurrentUserOwnLock(Object_Lock__c lock) {
        return lock.User__c == UserInfo.getUserId();
    }

    public static Datetime getExpirationDatetime(String sObjectId) {
        LockerConfig.GetConfigResult result = LockerConfig.getObjectLockConfig(sObjectId);
        LockerConfig.ObjectConfig config = result.config;

        if (config.timeout != null || config.timeout > 0) {
            return Datetime.now().addMinutes(config.timeout);
        }

        return null;
    }

    public static Boolean isLockExpired(Object_Lock__c lock) {
        return lock.Expires_At__c <= Datetime.now();
    }
}