force-app/main/default/objects/Object_Lock__c/Object_Lock__c.object-meta.xml
<CustomObject>
    <label>Object Lock</label>
    <nameField>
        <displayFormat>OBJLCK-{0000}</displayFormat>
        <label>Object Lock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Locks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Lock__c/fields/Expires_At__c.field-meta.xml
<CustomField>
    <fullName>Expires_At__c</fullName>
    <description>Time after which this lock is no longer valid.</description>
    <label>Expires At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Object_Lock__c/fields/sObject_Id__c.field-meta.xml
<CustomField>
    <fullName>sObject_Id__c</fullName>
    <description>Record ID of the sObject being locked.</description>
    <label>sObject ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Lock__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user that owns this lock.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Object_Locks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LockedObjectTriggerHandler.cls
public with sharing class LockedObjectTriggerHandler {
    
    public static SaveResult handle(Map<Id, SObject> sObjects) {

        List<Object_Lock__c> locks = [
            SELECT sObject_Id__c, Expires_At__c, User__c
            FROM Object_Lock__c 
            WHERE sObject_Id__c IN :sObjects.keySet()
        ];

        List<Object_Lock__c> locksToDelete = new List<Object_Lock__c>();
        LockValidator validator = new LockValidator();
        SaveResult result = new SaveResult(true);

        for (Object_Lock__c lock : locks) {
            if (validator.doesCurrentUserOwnLock(lock) || validator.isLockExpired(lock)) {
                locksToDelete.add(lock);
            }
            else {
                result = new SaveResult(false, 'Unable to save due to one or more locked records.');
                sObjects.get(lock.sObject_Id__c).addError('Cannot save locked record.');
            }
        }

        if (locksToDelete.size() > 0) {
            delete locksToDelete;
        }

        return result;
    }

    public class SaveResult extends BaseResult {
        public SaveResult(Boolean didSucceed) {
            this(didSucceed, null);
        }

        public SaveResult(Boolean didSucceed, String message) {
            super(didSucceed, message);
        }
    }
}