force-app/main/default/objects/Object_Lock__c/Object_Lock__c.object-meta.xml
<CustomObject>
    <label>Object Lock</label>
    <nameField>
        <displayFormat>OBJLCK-{0000}</displayFormat>
        <label>Object Lock Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Object Locks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Object_Lock__c/fields/Expires_At__c.field-meta.xml
<CustomField>
    <fullName>Expires_At__c</fullName>
    <description>Time after which this lock is no longer valid.</description>
    <label>Expires At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Object_Lock__c/fields/sObject_Id__c.field-meta.xml
<CustomField>
    <fullName>sObject_Id__c</fullName>
    <description>Record ID of the sObject being locked.</description>
    <label>sObject ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Object_Lock__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user that owns this lock.</description>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Object_Locks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/LockValidator.cls
public with sharing class LockValidator implements ILockValidator {
    
    public CanLockResult canLockObject(String sObjectId) {

        List<Object_Lock__c> locks = [
            SELECT Id, Expires_At__c, User__r.Name 
            FROM Object_Lock__c 
            WHERE sObject_Id__c = :sObjectId
        ];

        List<Object_Lock__c> activeLocks = new List<Object_Lock__c>();
        List<Object_Lock__c> expiredLocks = new List<Object_Lock__c>();

        for (Object_Lock__c lock : locks) {
            (lock.Expires_At__c > Datetime.now() ? activeLocks : expiredLocks).add(lock);
        }

        delete expiredLocks;

        if (activeLocks.size() != 0) {
            return new CanLockResult(false, activeLocks[0].User__r.Name);
        }

        return new CanLockResult(true);
    }

    public Boolean doesCurrentUserOwnLock(Object_Lock__c lock) {
        return lock.User__c == UserInfo.getUserId();
    }

    public Boolean isLockExpired(Object_Lock__c lock) {
        return lock.Expires_At__c <= Datetime.now();
    }

    public class CanLockResult extends BaseResult {
        public Boolean canLockRecord;
        public String lockedByUserDisplayName;

        public CanLockResult(Boolean canLockRecord) {
            this(canLockRecord, null);
        }

        public CanLockResult(Boolean canLockRecord, String lockedByUserDisplayName) {
            super(true);
            this.canLockRecord = canLockRecord;
            this.lockedByUserDisplayName = lockedByUserDisplayName;
        }
    }
}